### ISSUE TITLE
WFS Abfrage selbst bauen

### ISSUE THREAD

**Issue by eikerossow** [gellweiler/net.gellweiler.geodaten#1]
Hi,

ich bin auf dein Git gestoßen als ich mich mit der Regionalschlüssel Thematik befasst habe. Leider sind die Dokumentationen von offizieller Seite (geodatenzentrum.de) nicht sehr hilfreich weswegen ich mich an deiner Lösung orientiert habe.

Ich möchte einen Parser für den Regionalschlüssel bauen, ich hab soweit verstanden das ich die BBOX in Form von Lat und Lon übergeben muss und im Idealfall den darin befindlichen Regionalschlüssel etc. bekomme.

Leider bekomme ich es nicht ganz zum hin, meine URL hab ich so gebaut:

http://sg.geodatenzentrum.de/wfs_vg2500?request=GetFeature&service=wfs&version=1.2.0&propertyName=vg250:GEN,vg250:RS&bbox=10.588466,51.231319,10.588466,51.231319,EPSG:4326&typeName=vg250:Bundesland

Der von die verwendete typeName erschließt sich mir nicht.

Kannst du mit weiterhelfen?

**Comment by gellweiler** [comment]
http://www.geodatenzentrum.de/docpdf/geokodierungsdienst.pdf
http://www.geodatenzentrum.de/docpdf/vg250.pdf
